#include <furi.h>
#include <gui/gui.h>

/* generated by fbt from .png files in images folder */
#include <sampleapp_icons.h>

void draw_view_callback(Canvas* canvas, void* ctx) {
    UNUSED(ctx);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 35, 28, "Hello world");
    canvas_draw_str(canvas, 25, 40, "I'm sampleapp!");
}

int32_t sampleapp_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm sampleapp!");

    ViewPort* view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, draw_view_callback, 0);
    Gui* gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    furi_delay_ms(2000);

    gui_remove_view_port(gui, view_port);
    view_port_free(view_port);
    furi_record_close(RECORD_GUI);

    return 0;
}
